name: DARK-NOVA-XMD
services:
  - name: DARK-NOVA-XMD-service
    type: web
    ports:
      - 9090
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin