name: Deploy DARK-NOVA-XMD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Create sessions directory
      run: mkdir -p sessions

    - name: Create config.env from environment variables
      run: |
        echo "SESSION_ID=${{ secrets.SESSION_ID }}" > config.env
        echo "PREFIX=${{ secrets.PREFIX || '.' }}" >> config.env
        echo "MODE=${{ secrets.MODE || 'public' }}" >> config.env
        echo "OWNER_NUMBER=${{ secrets.OWNER_NUMBER }}" >> config.env
        echo "BOT_NAME=${{ secrets.BOT_NAME || 'DARK-NOVA-XMD' }}" >> config.env
        echo "ALWAYS_ONLINE=${{ secrets.ALWAYS_ONLINE || 'false' }}" >> config.env
        echo "AUTO_STATUS_SEEN=${{ secrets.AUTO_STATUS_SEEN || 'true' }}" >> config.env
        echo "AUTO_STATUS_REACT=${{ secrets.AUTO_STATUS_REACT || 'true' }}" >> config.env
        echo "ANTI_LINK=${{ secrets.ANTI_LINK || 'true' }}" >> config.env
        echo "ANTI_DEL=${{ secrets.ANTI_DEL || 'true' }}" >> config.env
        echo "WELCOME=${{ secrets.WELCOME || 'true' }}" >> config.env

    - name: Start application
      run: |
        npm start &
        sleep 30

    - name: Keep alive with health check
      run: |
        for i in {1..30}; do
          curl -f http://localhost:9090 && exit 0
          sleep 10
        done
        exit 1
